### ISSUE TITLE
Zotero script timeouts

### ISSUE THREAD

**Issue by kwcooper** [GCCR/GCCR.github.io#54]
@cbouy Occasionally the Zotero script posts a timeout error, which breaks a bit of the build process. 

Not a big deal, and either could be due to too many commits in rapid secession (not sure what their API call limit is) or just some server error during the handshake. In any case, it may be worth keeping in the back of our heads. 

Perhaps putting non-essental calls in a try/except statement so the build process can at least run through properly. Not sure if we can catch errors through github actions to our own log file, but that may be preferred. 

Below is the traceback if you're curious. 

`Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 431, in _retrieve_data
    self.request.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.zotero.org/groups/2503085/items?limit=100&sort=dateAdded&start=500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_scripts/zotero_to_yml.py", line 68, in <module>
    for item in z.everything(z.items(sort="dateAdded", direction="desc")):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 913, in everything
    items.extend(self.follow())
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 198, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 433, in _retrieve_data
    error_handler(self, self.request)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 1645, in error_handler
    raise ze.HTTPError(err_msg(req))
pyzotero.zotero_errors.HTTPError: 
Code: 500
URL: https://api.zotero.org/groups/2503085/items?limit=100&sort=dateAdded&start=500
Method: GET
Response: An error occurred`

**Comment by kwcooper** [comment]
I think I fixed this...
